### PR TITLE
add csp trusted types policy

### PR DESCRIPTION
**Pull request by keithamus**
This adds the `setCSPTrustedTypePolicy` static method to the `AutoCompleteElement`, allowing userland code to attach a trusted types policy to the element.

This is similar to the work done in https://github.com/github/include-fragment-element/pull/81 by @lgarron.

### CODE REVIEW

**Comment by primer-css** [comment]
:wave: Hello and thanks for pinging us! This issue or PR has been added to our inbox and a Design Infrastructure first responder will review it soon.
- :art: **If this is a PR that includes a visual change**, please make sure to add screenshots in the description or deploy this code to a lab machine with instructions for how to test.
- :fast_forward: **If this is a PR that includes changes to an interaction**, please include a [video recording](https://support.apple.com/en-us/HT208721) in the description.
- :warning: **If this is urgent**, please visit us in [#primer](https://github.slack.com/archives/CSGAVNZ19) on Slack and tag the first responders listed in the channel topic.

**Review by rzhade3 — APPROVED** [review]
Looks good to me!

**Review by fletchto99 — APPROVED** [review]
This looks good to me! Thanks for proactively updating our libraries to support trusted types.

**Comment by lgarron** [comment]
> This is similar to the work done in [github/include-fragment-element#81](https://github.com/github/include-fragment-element/pull/81) by @lgarron.

ohai!

Looking pretty good to me, but of course it's in y'allses hands now. 😃

**Comment by KyFaSt** [comment]
hi @keithamus thanks for taking initiative on this, is there anything we can do to support you getting this into github/github?

**Pull request merged**
